// Mocks generated by Mockito 5.4.5 from annotations
// in roadsurfer_challenge/test/repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:roadsurfer_challenge/api/abstract_api.dart' as _i2;
import 'package:roadsurfer_challenge/api/repository.dart' as _i3;
import 'package:roadsurfer_challenge/model/campsite.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCampsiteApi_0 extends _i1.SmartFake implements _i2.CampsiteApi {
  _FakeCampsiteApi_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CampsiteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCampsiteRepository extends _i1.Mock
    implements _i3.CampsiteRepository {
  MockCampsiteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CampsiteApi get api =>
      (super.noSuchMethod(
            Invocation.getter(#api),
            returnValue: _FakeCampsiteApi_0(this, Invocation.getter(#api)),
          )
          as _i2.CampsiteApi);

  @override
  _i4.Future<List<_i5.Campsite>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i4.Future<List<_i5.Campsite>>.value(<_i5.Campsite>[]),
          )
          as _i4.Future<List<_i5.Campsite>>);
}
