name: roadsurfer_challenge
description: "A Flutter web app for browsing, filtering, and displaying individual campsites – developed as a coding challenge, inspired by Roadsurfer Spots."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0-323.0.dev

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.1
  flutter_map: ^6.1.0
  flutter_riverpod: ^2.4.0
  http: ^1.2.0
  intl: ^0.19.0
  latlong2: ^0.9.0
  shared_preferences: ^2.2.0

### How to run? --> flutter pub run flutter_launcher_icons:main
### android: "ic_launcher_round"
### ios: "AppIcon"
flutter_icons:
  ios: true
  android: "square"
  image_path: "assets/app_icon/square.png"

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_image_test_utils: ^1.0.0
  flutter_lints: ^5.0.0
  mockito: ^5.4.2

dependency_overrides:
  analyzer: 7.3.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/app_icon/
    - assets/countries/
